### PR TITLE
Add coursier

### PR DESCRIPTION
**Pull request by kubukoz**

### CODE REVIEW

**Comment by tues** [comment]
Isn't it better to enable Coursier globally in your `~/.sbt/` instead?

**Comment by kubukoz** [comment]
Maybe. But it won't work in CI :P

**Comment by tues** [comment]
It'll be a very unpleasant surprise when someone clones this project, runs `sbt` and it suddenly starts to re-download all JVM libraries commonly used in the Scala ecosystem. I'm sure there are better ways to enable Coursier in CI... I might try doing that later today.

**Comment by kubukoz** [comment]
Sure, go ahead. I don't know how to do that :P

**Comment by krzemin** [comment]
We were using coursier some time ago (it was one of the 1.0.0-RCxx version), but it was causing random problems on CI so that I went back to sbt.

**Pull request closed without merging**
