### PR TITLE
Change how logos are being displayed

### PR DESCRIPTION
**Pull request by MateuszKubuszok**
Display logo in circle, centered on both README and landing page of docs

### CODE REVIEW

**Comment by NoemiRozpara** [comment]
The logo seems to not be centered in `README`: 
image

Also I'd suggest putting the plain version everywhere on Github - as GH can be either in light or dark mode. The dark circle doesn't look too good on the dark background. The intention was to use the dark circle on the light background and the other way round. So I'd say either the orange one, or none 🙂 The circle may look good in avatars and tiny previews ✨

**Comment by MateuszKubuszok** [comment]
> The logo seems to not be centered in `README`: image

Ups, I pressed merge before this comment appeared. Yes, it seems that [GH actively removes `style` tags](https://stackoverflow.com/questions/44831505/which-inline-html-styles-does-github-markdown-accept) :/

> Also I'd suggest putting the plain version everywhere on Github - as GH can be either in light or dark mode. The dark circle doesn't look too good on the dark background. The intention was to use the dark circle on the light background and the other way round. So I'd say either the orange one, or none 🙂 The circle may look good in avatars and tiny previews ✨

Actually, I tested it dark mode, I haven't used light mode in years. [Same with docs](https://chimney--448.org.readthedocs.build/en/448/).

**Comment by MateuszKubuszok** [comment]
@NoemiRozpara  Should be better now.

**Comment by NoemiRozpara** [comment]
Awesome! 🙌

**Pull request merged**
