### PR TITLE
Improve support for value classes

### PR DESCRIPTION
**Pull request by ekhov**
Implementation of #249

- [x] Add rewrapping value of one value class to another value class if value is the same type.
      ```case class Foo(t: T) extends AnyVal => case class Bar(t: T) extends AnyVal```

- [ ] Add unwrapping of a value class's value of one type(`T`) to another type(`S`) if `T => S` transformer exists.
       ```case class Foo(t: T) extends AnyVal => S```
       
- [ ] Add wrapping a value of one type(`T`) to value class of another type(`S`) if `T => S` transformer exists.
       ```T => case class Foo(s: S)```
       
- [ ]  Add rewrapping value(type `T`) of one value class to another value class(with value of type `S`  if `T => S` transformer exists.
        ```case class Foo(t: T) => case class Bar(s: S)```

### CODE REVIEW

**Comment by MateuszKubuszok** [comment]
@ekhov hello, thanks for the contribution :) If you want to work on the issue it's great! but please wait a day of two, because we are about to review and merge https://github.com/scalalandio/chimney/pull/235 and it would cause a lot of conflicts and issues for you, if you used the current `master`.

**Comment by MateuszKubuszok** [comment]
Hey, it took us some time but we've merged it finally. If you are interested with working on this issue, now it's possible :)

**Comment by ekhov** [comment]
@MateuszKubuszok Yay! Thanks for letting me know! Yes, I'm still interested, will take a look in the coming days

**Comment by ekhov** [comment]
Updated version: https://github.com/scalalandio/chimney/pull/265

**Pull request closed without merging**
