### PR TITLE
Support for scope-default transformer configuration

### PR DESCRIPTION
**Pull request by krzemin**
This PR addresses #176. It's result of several prototyping rounds made in cooperation with @d12frosted.

More or less it implements the plan sketched here: https://github.com/scalalandio/chimney/issues/176#issuecomment-669329379 

TODO:
- [X] more test cases, especially of newly added flags combinations
- [X] ~~provide analogous mechanism for patchers~~ let's have it as a separate issue (https://github.com/scalalandio/chimney/issues/191)
- [X] rethink naming and placement of newly added types
- [x] update docs

### CODE REVIEW

**Review by d12frosted — APPROVED** [review]
LGTM, next step would be to pass default flags from top to the very bottom 💯 

Thank you for taking your time to try this idea.

**Comment by krzemin** [comment]
> next step would be to pass default flags from top to the very bottom

@d12frosted it's already supported, see these test cases: https://github.com/scalalandio/chimney/pull/190/files#diff-8bf852c2438394dc69a2bd644c2a815eR1017 Or do you mean something else?

**Comment by d12frosted** [comment]
🤔 yeah, you are right. For some reason I was confused since I didn't see ability to pass configuration to `Transformer.define`. But looking at the tests - seems like it works 😸 thanks

**Comment by krzemin** [comment]
> For some reason I was confused since I didn't see ability to pass configuration to Transformer.define.

Good point, let me elaborate.

Initially I thought that capturing implicit flags on `Transformer.define` and encoding them in the `Transformer(F)Defnition` would be a simple and clean idea. But to capture types passed by implicit instance, we would need third type parameter (for flags) and just calling it as `Transformer.define[From, To]` would not be possible any more.

I could fix it by making `.define` a whitebox macro and look for implicit inside, but... there is a simpler solution: 
- build `Transformer(F)Definition` flags on top of `TransformerFlags.Default`
- require scoped flags only in `.buildTransformer`
- merge both flags stacks after capturing both types

It keeps almost the same semantics, but bring less troubles for the users.

**Comment by d12frosted** [comment]
@krzemin ah I see. This is something I didn't consider in my PRs. Nicely done!

**Review by ulanzetz — APPROVED** [review]

**Comment by d12frosted** [comment]
This is wonderful! Thank you @krzemin 🎉

**Comment by krzemin** [comment]
Thank you for your efforts too @d12frosted!

**Pull request merged**
